export interface User {
  userID: String,
  companyID: String,
  role: String,
  username: String,
  email: String,
  phone: String,
  avatar: String,
  profile: String,
  status: String,
  createdAt: String,
  updatedAt: String,
  createdBy: String,
  updatedBy: String,
}
